# *****************************************************
# *** Create the table structure for the table 'film' *****
# *****************************************************

DROP TABLE IF EXISTS `film`;
CREATE TABLE IF NOT EXISTS `film` (
  `filmID` mediumint(9) NOT NULL default '0',
  `title` varchar(255) default NULL,
  `categoryName` varchar(20) NOT NULL default '',
  `notes` text,
  PRIMARY KEY (`filmID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

# *****************************************************
# ***Insert record data for the table `film`**********
# *****************************************************

INSERT INTO `film` (`filmID`, `title`, `categoryName`, `notes`) VALUES
(138, 'working girl', 'comedy', NULL),
(23, 'la testament d''orphee', 'classic', ''),
(5, 'my darling clementine', 'epic', 'Henry Fonda'),
(59, 'i vitteloni', 'drama', ''),
(68, 'handsworth songs', 'drama', ''),
(73, 'fitscarraldo', 'drama', ''),
(227, 'hunchback of notre dame,', 'classic', '1939 remake of the Lon Chaney silent movie.  Charles Laughton and Maureen O''Hara'),
(78, 'seventh seal, the', 'drama', ''),
(87, 'long goodbye, the', 'drama', ''),
(89, 'smithereens', 'drama', ''),
(90, 'invitation, the', 'drama', ''),
(92, 'whale nation', 'documentary', ''),
(94, 'conversation, the', 'thriller', ''),
(95, 'long good friday, the', 'thriller', ''),
(96, 'danton', 'drama', ''),
(98, 'missing', 'drama', ''),
(102, 'les visiteurs du soir', 'drama', ''),
(103, 'quatre cent coups', 'drama', ''),
(104, 'les mistons', 'drama', ''),
(105, 'blood sweat & tears', 'drama', ''),
(107, 'rhinoceros', 'drama', ''),
(108, 'tirez sur le pianist', 'comedy', ''),
(113, 'grapes of wrath', 'classic', ''),
(114, 'guys & dolls', 'music', 'Luck be a Lady, Sid Down you''re rockin the boat, gamblers and gals, but the colour of the tie you are wearing I''ll wager you know not.'),
(116, 'last year at marienbad', 'drama', ''),
(124, 'hustler, the', 'classic', ''),
(128, 'last picture show, the', 'drama', ''),
(131, 'le jour se leve', 'thriller', ''),
(140, 'rollerball', 'sci-fi', ''),
(142, 'getaway, the', 'drama', ''),
(143, 'raging bull', 'drama', ''),
(150, 'brimstone & treacle', 'horror', ''),
(153, 'bolweiser', 'drama', ''),
(154, 'death in venice', 'drama', ''),
(157, 'top hat', 'classic', ''),
(158, 'carefree', 'classic', ''),
(167, 'serpico', 'drama', ''),
(170, 'stand up nigel barton', 'drama', ''),
(172, 'caravaggio', 'drama', ''),
(174, 'hitch-hiker''s guide', 'comedy', ''),
(175, 'where the green ants drea', 'drama', ''),
(176, 'ghosts in the machine', 'documentary', ''),
(178, 'la peau douce', 'drama', ''),
(179, 'singing detective part 2', 'drama', ''),
(181, 'singing detective part 4', 'drama', ''),
(182, 'drowning pool', 'drama', ''),
(184, 'wall, the', 'drama', ''),
(185, 'around the world in 80 days', 'comedy', ''),
(186, 'don''t look back', 'documentary', ''),
(191, 'lady vanishes, the', 'drama', ''),
(194, 'spellbound', 'classic', ''),
(195, 'hammet', 'drama', ''),
(196, 'cabinet of dr caligari', 'drama', ''),
(197, 'robin hood', 'drama', ''),
(199, 'gimme shelter', 'music', ''),
(201, 'painting in light', 'documentary', ''),
(203, 'play it again sam', 'comedy', ''),
(204, 'it was twenty years ago today', 'documentary', ''),
(206, 'treasure of the sierra madre', 'classic', ''),
(210, 'maltese falcon, the', 'classic', ''),
(215, 'notorious', 'classic', ''),
(217, 'swingtime', 'classic', ''),
(219, 'talking heads', 'documentary', ''),
(224, 'wise blood', 'drama', ''),
(247, 'five easy pieces', 'drama', ''),
(248, 'play it again sam', 'comedy', ''),
(249, 'rashomon', 'drama', ''),
(58, 'heaven''s gate', 'epic', 'A lyrical though sometimes savage story about the west.  With John Hurt and has one of the best waltz scenes this side of the Pecos.'),
(82, 'annie hall', 'comedy', 'After breaking up with his girlfriend Annie Hall, neurotic comedian Alvy Singer goes on a stream of conciousness journey through his memories of their relationship, trying to find out what caused them to part ways. He often breaks the fourth wall, speaking to the camera, entering peoples'' stories, and even using animation.'),
(134, 'themroc', 'comedy', 'An amusing, surreal, relentless satirical swipe at the banality of the rat race.'),
(7, 'catch 22', 'comedy', 'Based on the book by Joseph Heller.  A sometimes surreal black comedy about war.  Milo Milobender (John Voight) who is trying to make a deal with anybody in order to make a buck. Yosarian who thinks everyone is trying to kill him.'),
(33, 'paris texas', 'drama', 'Beautiful landscapes and haunting music from Ry Cooder.  The story of a man who having wandered around America after splitting up with his wife, returns to meet his child, reared by his brother and rediscover his past.  With Harry Dean Stanton and Natasha Kinski.'),
(126, 'babylon', 'drama', 'Brinsley Ford.  The movie centers around Brindsley Forde''s character blue. He fronts a reggae sound system based in west London. The movie captures the trials and tribulations of young black youths in troubled London in the early eighties.'),
(85, 'she', 'classic', 'CLASSIC '),
(152, 'atfer hours', 'comedy', 'Comedy of errors, person goes out at night and has a measure of bad luck.'),
(228, 'easter parade', 'music', 'directed by Charles Walters, with Judy Garland and Fred Astaire.'),
(54, 'deerhunter, the', 'drama', 'Do I like this movie, I''m not sure I do.'),
(51, 'burden of dreams', 'documentary', 'Documentary about the making of Fitzcarraldo by Hertzog.'),
(162, 'blood wedding', 'classic', 'Electric and moving dance-mime of a Garcia Lorca story.  Spanish music and dancing.  It''s a hairs on the back of the neck job.'),
(9, 'thirty nine steps', 'classic', 'Fabulous film with Robert Donat as the hero eluding and ultimately, and I hope I''m not giving the game away here, thwarting the german villains.'),
(156, 'african queen', 'classic', 'Humphrey Bogart, Katherine Hepburn, Robert Morley - James Agee was the writer of the screenplay based on a novel by C.S. Forester.  There is surely no one out there who doesn''t know the plot.'),
(137, 'big sleep, the', 'classic', 'Humphrey Bogart, Lauren Bacall '),
(222, 'casablanca', 'classic', 'I thought I told you never to play that song.'),
(155, 'bullitt', 'drama', 'Isn''t this the film with the great car chase with Ali MacGraw?'),
(223, 'chinatown', 'comedy', 'Jack Nicholson and Faye Dunnaway.  Good film, he''s great as the Marlowe type figure.'),
(165, 'big heat, the', 'classic', 'Lee Marvin, Gloria Grahame, Glenn Ford, Jocelyn Brando.  Kev things this is one of the greatest movies ever.  Poor Gloria gets coffee in the face from Lee Marvin, she reciprocates later in the film much too his annoyance.'),

(117, 'diner', 'drama', 'Mickey Rourke, Ellen Barkin, college kids go get something to eat. Mickey Rourke plays one of the only non-fag hairdressers in Hollywood history.'),
(22, 'orphee', 'classic', 'Orphee is a poet who becomes obsessed with Death (the Princess). They fall in love. Orphee''s wife, Eurydice, is killed by the Princess'' henchmen and Orphee goes after her into the Underworld. Although they have become dangerously entangled, the Princess sends Orphee back out of the Underworld, to carry on his life with Eurydice.'),
(66, '1900 part 2', 'epic', 'part 1 and notes are on video 64'),
(53, 'rumble fish', 'buddy', 'Shot in black and white, with the ''rumble fish'' as the only thing in colour, with Mickey Rourke as motorcycle boy, Dennis Hopper as his father.  Moody is what I think you''d call it.'),
(119, 'alice in wonderland', 'drama', 'The best version of Alice I''ve seen.  Very surreal, with Peter Cook, John Geilgud and many other famous faces.  The are some wonderful images in it... great photography.'),
(91, 'seven samurai', 'classic', 'The film which inspired the making of The Magnificent Seven.  Stars the genius Toshiro Mifune.'),
(31, 'vivement dimanche', 'thriller', 'Truffault homage to film noir.  The hero gets framed for murder his only ally a secretary who doesn''t like him very much.');

